### ISSUE TITLE
cannot select the database of notion

### ISSUE THREAD

**Issue by mhh0318** [denkiwakame/arxiv2notion#1]
[validation_error] body failed validation. Fix one: body.parent.database_id should be a valid uuid, instead was `""`. body.parent.page_id should be defined, instead was `undefined`.

I've invite the integrations on the database page.
![image](https://user-images.githubusercontent.com/42776955/137613414-786ca824-4db9-4618-be3f-f8f91a272d31.png)

**Comment by mhh0318** [comment]
Now I can select the database from notion, there is another error...
[validation_error] Title is expected to be rich_text.

**Comment by xinyouduogao** [comment]
> [validation_error] body failed validation. Fix one: body.parent.database_id should be a valid uuid, instead was `""`. body.parent.page_id should be defined, instead was `undefined`.
> 
> I've invite the integrations on the database page. ![image](https://user-images.githubusercontent.com/42776955/137613414-786ca824-4db9-4618-be3f-f8f91a272d31.png)

How did you solve it? THX!

**Comment by mhh0318** [comment]
> > [validation_error] body failed validation. Fix one: body.parent.database_id should be a valid uuid, instead was `""`. body.parent.page_id should be defined, instead was `undefined`.
> > I've invite the integrations on the database page. ![image](https://user-images.githubusercontent.com/42776955/137613414-786ca824-4db9-4618-be3f-f8f91a272d31.png)
> 
> How did you solve it? THX!

Hi, I just create the database page again exactly follwing the instructions.

**Comment by denkiwakame** [comment]
@mhh0318 @xinyouduogao 

Hi, thank you for reporting the issue. Let me supplement the instruction https://github.com/denkiwakame/arxiv2notion#getting-started

## 1. Create a new database (table)
![image](https://user-images.githubusercontent.com/1871262/137677203-d8ae68e4-3e38-4921-8c42-cd16277ece26.png)

## 2. Set the database columns with "specified names and properties".
> [validation_error] Title is expected to be rich_text.

- e.g. The property of 'Title' is expected to be `Title (rich_text)`, 
- The each columns should have the following titles and properties.
  -  Each title and property **should be strictly consistent with the following.**

|property name | property type|
|-----|-----|
|Title|Title|
|URL|URL|
|Publisher|Select|
|Authors|Text|
|Abstract|Text|

![image](https://user-images.githubusercontent.com/1871262/137678691-81ea8efa-7cb1-46b1-b7ab-b069b9fd1640.png)

## 3. Invite the integration via "Share" on the database page

![image](https://user-images.githubusercontent.com/1871262/137679875-0a5a4c89-b224-48e9-a09e-cc37a5dd714d.png)

## 4. Setup integration ID
- Strictly follow the instructions https://github.com/denkiwakame/arxiv2notion#setup
- You will be able to select your created databases in the Chrome extension popup.

![image](https://user-images.githubusercontent.com/1871262/137677472-deb26dd0-ba5a-4662-ab21-be5edfdb89ba.png)

> database_id should be a valid uuid

- The extension retrieves your databases via Notion API https://developers.notion.com/reference/retrieve-a-database
  - https://github.com/denkiwakame/arxiv2notion/blob/main/src/js/notion.js#L138-L162
- If you have neither created databases nor allowed integration, the extension will fail to retrieve the database ID.

I hope this helps.

**Comment by denkiwakame** [comment]
Btw, I just realized that several useful APIs were newly released after I created this arXiv2notion https://developers.notion.com/changelog
I will be considering to update this extension for easier and more flexible setup.
