### ISSUE TITLE
New version Edge can't work

### ISSUE THREAD

**Issue by cb11711211** [denkiwakame/arxiv2notion#2]
When I try to work in chromium version edge, and following the instruction of the author, I still can not get the arXiv paper transfer to notion correctly. And the problem I met is that there is no selection of database page of notion when I click the extension icon on the page of paper. The mistake could be performing URL incorrectly.

**Comment by denkiwakame** [comment]
@cb11711211 

Hi, I guess this is not the problem specific to the Chromium Edge.
Now I confirmed that the extension successfully work with the Microsoft Edge (version of 94.0.992.50 / x86_64 / Mac OS X). 

<img src="https://user-images.githubusercontent.com/1871262/137872383-9acc0e97-bef8-4a74-8dcc-e5ab28407404.png" width="400">

>  there is no selection of database page of notion when I click the extension icon on the page of paper.

Could you please confirm the following items?
- [ ] **You have logged in to notion.so** in your Edge browser
- [ ] You have created database NOT by /database
- [ ] You have created ‪a ‪new integration and invited the integration to the target database page on notion.so https://github.com/denkiwakame/arxiv2notion#getting-started
- [ ] You have correctly set up integration ID via options of the extension, and got a message `Successfully connected with notion.so` https://github.com/denkiwakame/arxiv2notion#setup

For more detailed instruction, please see also https://github.com/denkiwakame/arxiv2notion/issues/1#issuecomment-945416804
